Chatbot pull request
LibertyWalkKato/NIX_java_education_Vykhodtsev_Vadym pull request #2
Opened 2021-10-13 19:36 UTC by LibertyWalkKato

Chatbot 2-st stage

Chatbot 3-th stage

Chatbot 4-st stage

Chatbot 5-st stage

2021-10-13 19:57 UTC, MaximSomochkin requested changes

2021-10-13 19:57 UTC, MaximSomochkin commented on src/nix/education/java/chatbot/ChatBot.java
> +            if (answer == 2) break;
В компаниях любят так:
 if (answer == 2){
 System.out.printf("You right!\nGoodbye, have a nice day!"); // логику лучше не разрывать
 break;
}

2021-10-13 20:04 UTC, LibertyWalkKato commented
Понял, что я должен сделать в таком случае?

ср, 13 окт. 2021 г. в 22:57, MaximSomochkin ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/nix/education/java/chatbot/ChatBot.java
> <https://github.com/LibertyWalkKato/NIX_java_education_Vykhodtsev_Vadym/pull/2#discussion_r728398317>
> :
>
> > +        remainder5 = in.nextInt();
>
> +        remainder7 = in.nextInt();
>
> +        age = (remainder3 * 70 + remainder5 * 21 + remainder7 * 15)%105;
>
> +        System.out.printf("Your age is %d that's a good time to start programming\nNow I will prove to you that I can count to any positive number you want.\n",age);
>
> +        int count  = in.nextInt();
>
> +        for (int i = 0; i <= count; i++) {
>
> +            System.out.printf("%d !\n",i);
>
> +        }
>
> +        System.out.printf("Let's test your programming knowledge.\nWhy do we use methods?\n");
>
> +        System.out.printf("1. To repeat a statement multiple times.\n"
>
> +                +"2. To decompose a program into several small subroutines.\n"
>
> +                +"3. To determinate the execution time of a program.\n"
>
> +                +"4. To interrupt the execution of a program.\n");
>
> +        do {
>
> +            answer = in.nextInt();
>
> +            if (answer == 2) break;
>
>
> В компаниях любят так:
> if (answer == 2){
> System.out.printf("You right!\nGoodbye, have a nice day!"); // логику
> лучше не разрывать
> break;
> }
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/LibertyWalkKato/NIX_java_education_Vykhodtsev_Vadym/pull/2#pullrequestreview-779025421>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVYYINL6ZZNN7ZE4Y7ZUWALUGXQCFANCNFSM5F566IVA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-13 20:17 UTC, MaximSomochkin commented
Перепиши залей на пулреквест

2021-10-15 20:30 UTC, MaximSomochkin approved these changes
Сливай ветку

2021-10-16 08:36 UTC, merged

2021-10-22 19:30 UTC, asrubel reviewed
Привет, в следущий раз сжимай коммиты в один с помощью ребейса перед слиянием.